# Generated by Django 2.0.5 on 2023-07-06 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enpApi', '0042_auto_20211206_0444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ethicalfeedback',
            unique_together={('user', 'module_id', 'scene')},
        ),
    ]
