# Generated by Django 2.0.5 on 2023-07-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enpApi', '0043_auto_20230706_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='registration_type',
            field=models.CharField(default='Respondent', max_length=16),
        ),
    ]
